### ISSUE TITLE
.to() is incompatible with pytz.timezone

### ISSUE THREAD

**Issue by ograycode** [crsmithdev/arrow#154]
It looks like at least ``to()`` is incompatible with pytz.timezone. This is especially concerning because pytz is so widely used, and integrated into Django. Because of this, arrow is incompatible with [djanog.utils.timezone.get_default_timezone](https://sourcegraph.com/github.com/django/django/.PipPackage/Django/.def/django/utils/timezone/get_default_timezone) 

It is currently PDT time (offset of -7 from UTC).
```
In [3]: import arrow

In [4]: arrow.now()
Out[4]: <Arrow [2014-08-16T14:04:24.883067-07:00]>

In [5]: str(arrow.now().datetime)
Out[5]: '2014-08-16 14:04:37.988805-07:00'

In [6]: str(arrow.now())
Out[6]: '2014-08-16T14:04:47.148559-07:00'

In [7]: import pytz

In [10]: str(arrow.utcnow().to(pytz.timezone("America/Los_Angeles")).datetime)
Out[10]: '2014-08-16 14:10:52.073869-08:00' # Should be -7

In [11]: str(arrow.utcnow().to(pytz.timezone("America/Los_Angeles")))
Out[11]: '2014-08-16T14:11:05.067117-08:00' # Should be -7

In [12]: str(arrow.utcnow().to("America/Los_Angeles").datetime)
Out[12]: '2014-08-16 14:11:29.675558-07:00'

In [13]: str(arrow.utcnow().to("America/Los_Angeles"))
Out[13]: '2014-08-16T14:12:55.047974-07:00'
```

This was discovered using pytz==2014.2 and arrow==0.4.4.

**Comment by dekoza** [comment]
Any update on this?

**Comment by dekoza** [comment]
My results are even better:
str(arrow.utcnow().to(pytz.timezone("America/Los_Angeles")).datetime)
# Returns '2015-05-29 05:03:07.061851-07:53' # wait, what?!

pytz = 2015.2
arrow = 0.5.4

**Comment by andrewelkins** [comment]
I'd welcome a PR to address this @dekoza @ograycode @Exirel

**Comment by ograycode** [comment]
Aside from the merge conflicts, #155 resolves this but adds a dependency on pytz.

**Comment by Kudo** [comment]
Thanks @andrewelkins's merging for #254.
If #254 did fix this issue, maybe we can further close this.
Thanks.

**Comment by ColtonProvias** [comment]
Merge on #254 also fixed issue here where offset of America/New_York was being represented as -0456 instead of -0400 after being converted from UTC.  Tested on Python 3.4.3 and 3.5.0.  I'd say the issue is fixed here at least.

**Comment by ograycode** [comment]
Closing this issue. I never used arrow because of it, and it's being reported as fixed.

**Comment by rskumar** [comment]
Still not added in documentation? Couldn't find any example. 

It would be great if someone add it in timezone specific section, as people google to find quick examples.
